// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0122:Initializing field with default value is redundant", Justification = "It's not redundent, it's explicit. Better explicit than implicit.", Scope = "member", Target = "~F:Strev.QuickTools.ViewModel.BaseMainWindowVM._progress")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0122:Initializing field with default value is redundant", Justification = "It's not redundent, it's explicit. Better explicit than implicit.", Scope = "member", Target = "~F:Strev.QuickTools.Lib.Service.EntityDispatcher`1._disposed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0122:Initializing field with default value is redundant", Justification = "It's not redundent, it's explicit. Better explicit than implicit.", Scope = "member", Target = "~F:Strev.QuickTools.MainApp.BaseStarter._onStop")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0122:Initializing field with default value is redundant", Justification = "It's not redundent, it's explicit. Better explicit than implicit.", Scope = "member", Target = "~F:Strev.QuickTools.Service.InitDisposeManager._hasBeenInitialized")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0122:Initializing field with default value is redundant", Justification = "It's not redundent, it's explicit. Better explicit than implicit.", Scope = "member", Target = "~F:Strev.QuickTools.ViewModel.BaseScreenContainerVM._initialized")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0122:Initializing field with default value is redundant", Justification = "It's not redundent, it's explicit. Better explicit than implicit.", Scope = "member", Target = "~F:Strev.QuickTools.ViewModel.BaseScreenContainerVM._screenVmByName")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0122:Initializing field with default value is redundant", Justification = "It's not redundent, it's explicit. Better explicit than implicit.", Scope = "member", Target = "~F:Strev.QuickTools.ViewModel.BaseScreenContainerVM._screenVMs")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0029:Warns about property or indexer setters and event adders or removers that do not use the value parameter", Justification = "<Pending>", Scope = "member", Target = "~P:Strev.QuickTools.ViewModel.Generic.ChoiceVM.Text")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0029:Warns about property or indexer setters and event adders or removers that do not use the value parameter", Justification = "<Pending>", Scope = "member", Target = "~P:Strev.QuickTools.ViewModel.Generic.ChoiceVM.Command")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Code", "RECS0073:Redundant case label", Justification = "<Pending>", Scope = "member", Target = "~M:Strev.QuickTools.View.UserControls.Helpers.GetControlHeightByTextSize(Strev.QuickTools.DomainModel.Enumeration.TextSizeType)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Code", "RECS0073:Redundant case label", Justification = "<Pending>", Scope = "member", Target = "~M:Strev.QuickTools.View.UserControls.Helpers.GetFontSizeByTextSize(Strev.QuickTools.DomainModel.Enumeration.TextSizeType)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Notifications", "RECS0083:Shows NotImplementedException throws in the quick task bar", Justification = "<Pending>", Scope = "member", Target = "~M:Strev.QuickTools.View.Converters.BoolToColorConverter.ConvertBack(System.Object,System.Type,System.Object,System.Globalization.CultureInfo)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Notifications", "RECS0083:Shows NotImplementedException throws in the quick task bar", Justification = "<Pending>", Scope = "member", Target = "~M:Strev.QuickTools.View.Converters.BoolToVisibilityConvertor.ConvertBack(System.Object,System.Type,System.Object,System.Globalization.CultureInfo)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Notifications", "RECS0083:Shows NotImplementedException throws in the quick task bar", Justification = "<Pending>", Scope = "member", Target = "~M:Strev.QuickTools.View.Converters.TextSizeToHeightConverter.ConvertBack(System.Object,System.Type,System.Object,System.Globalization.CultureInfo)~System.Object")]