name: publish to nuget
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{secrets.NUGET_API_KEY}}
          nuget-version: '5.x'

      - name: dir
        run: dir

      - name: echo
        run: |
            echo "[${{ env.GITHUB_WORKSPACE }}] [${ env.GITHUB_WORKSPACE }] [$env:GITHUB_WORKSPACE]"

      - name: nuget restore
        env: 
            MSBUILD: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe
            SolutionDir: %env:GITHUB_WORKSPACE\src
        run: nuget restore src\projects\Strev.QuickTools\Strev.QuickTools.csproj

      - name: Build DotNET35
        env: 
            MSBUILD: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe
            SolutionDir: ${{env.GITHUB_WORKSPACE}}\src
        run: |
           cd "$env:GITHUB_WORKSPACE\src\projects\Strev.QuickTools"
           %MSBUILD% Strev.QuickTools.csproj

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: src\projects\Strev.QuickTools\Strev.QuickTools.csproj

          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: Strev.QuickTools

          # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
          # VERSION_FILE_PATH: Directory.Build.props

          # Regex pattern to extract version info in a capturing group
          # VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$

          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          VERSION_STATIC: 1.0.106

          # Flag to toggle git tagging, enabled by default
          # TAG_COMMIT: true

          # Format of the git tag, [*] gets replaced with actual version
          # TAG_FORMAT: v*

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          NUGET_SOURCE: https://api.nuget.org

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          # INCLUDE_SYMBOLS: false
